//
//  DetailBeerModels.swift
//  BeerList
//
//  Created by Lucas  N Santana on 25/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailBeer {
    // MARK: Use cases
    
    enum Show {
        struct Response {
            var beer: Beer?
        }
        struct ViewModel {
            struct BeerDetailed {
                var imageUrl: String?
                var name: String
                var tagline: String
                var abv: String
                var ibu: String
                var description: String
                
            }
            var beerDetailed : BeerDetailed
        }
    }
}
