//
//  DetailBeerInteractor.swift
//  BeerList
//
//  Created by Lucas  N Santana on 25/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBeerBusinessLogic {
    func showBeer()
}

protocol DetailBeerDataStore {
    var beer: Beer? { get set }
}

class DetailBeerInteractor: DetailBeerBusinessLogic, DetailBeerDataStore {
    
    var beer: Beer?
    
    var presenter: DetailBeerPresentationLogic?
    
    func showBeer() {
        let response = DetailBeer.Show.Response(beer: beer)
        presenter?.presentBeer(response: response)
    }
}
