//
//  ListBeerRouter.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBeerRoutingLogic {
    func routeToShowDetailBeer(segue: UIStoryboardSegue?)
}

protocol ListBeerDataPassing {
    var dataStore: ListBeerDataStore? { get }
}

class ListBeerRouter: NSObject, ListBeerRoutingLogic, ListBeerDataPassing {
    weak var viewController: ListBeerViewController?
    var dataStore: ListBeerDataStore?
    
    
    func routeToShowDetailBeer(segue: UIStoryboardSegue?){
        print("routeToShowDetailBeer segue \(segue)")
        viewController?.performSegue(withIdentifier: "ShowDetailBeer", sender: nil)
    }
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ListBeerViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ListBeerDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
