//
//  ListBeerWorker.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class ListBeerWorker {
    func requestBeers(completion: @escaping (ListBeer.FetchBeer.Response?) -> Void) {
        guard let url = URL(string: "https://api.punkapi.com/v2/beers") else {
            completion(nil)
            return
        }
        Alamofire.request(url,
                          method: .get,
                          parameters: ["include_docs": "true"])
            .validate()
            .responseJSON { response in
                guard response.result.isSuccess, let data = response.data else {
                        completion(nil)
                    return
                }
                do {
                    let listBeers =  try JSONDecoder().decode(Array<ListBeer.Beer>.self, from: data)
                    let response = ListBeer.FetchBeer.Response(listBeer: listBeers)
                    completion(response)
                } catch {
                    print(error)
                    completion(nil)
                }
        }
    }
}
