//
//  ListBeerModels.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListBeer {
    // MARK: Use cases
    
    enum FetchBeer {
        //    struct Request
        //    {
        //    }
        struct Response {
            var listBeer: [Beer]
        }
        struct ViewModel {
            var listBeer: [Beer]
        }
    }
    
    // MARK: - Beer
    struct Beer: Codable {
        let id: Int?
        let name, tagline, welcomeDescription: String?
        let imageURL: String?
        let abv: Double?
        let ibu: Double?
        
        enum CodingKeys: String, CodingKey {
            case id, name, tagline
            case welcomeDescription = "description"
            case imageURL = "image_url"
            case abv, ibu
        }
    }
    
}

