//
//  ListBeerInteractor.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBeerBusinessLogic {
    func requestBeers()
    func beerSelectTap(_ beer: ListBeer.Beer)
}

protocol ListBeerDataStore {
    var beerSelected: ListBeer.Beer? { get }
}

class ListBeerInteractor: ListBeerBusinessLogic, ListBeerDataStore {
    var presenter: ListBeerPresentationLogic?
    var worker: ListBeerWorker?
    var beerSelected: ListBeer.Beer?
    //MARK: ListBeerBusinessLogic
    
    func requestBeers() {
        worker = ListBeerWorker()
        worker?.requestBeers(completion: { (response) in
            var viewModel = ListBeer.FetchBeer.ViewModel(listBeer: [])
            if let listBeers = response {
                viewModel = ListBeer.FetchBeer.ViewModel(listBeer: listBeers.listBeer)
            }
            self.presenter?.presentListBeers(viewModel: viewModel)
        })
    }
    
    func beerSelectTap(_ beer: ListBeer.Beer){
        self.beerSelected = beer
        presenter?.presentDetailBeer()
    }
}
