//
//  ListBeerRouter.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBeerRoutingLogic {
    func routeToShowDetailBeer(segue: UIStoryboardSegue?)
}

protocol ListBeerDataPassing {
    var dataStore: ListBeerDataStore? { get }
}

class ListBeerRouter: NSObject, ListBeerRoutingLogic, ListBeerDataPassing {
    weak var viewController: ListBeerViewController?
    var dataStore: ListBeerDataStore?
    
    // MARK: Routing
    
    func routeToShowDetailBeer(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! DetailBeerViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToDetailBeer(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "DetailBeerViewController") as! DetailBeerViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToDetailBeer(source: dataStore!, destination: &destinationDS)
            navigateToDetailBeer(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToDetailBeer(source: ListBeerViewController, destination: DetailBeerViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetailBeer(source: ListBeerDataStore, destination: inout DetailBeerDataStore) {
      destination.beer = source.beerSelected
    }
}
