//
//  ListBeerModels.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListBeer {
    // MARK: Use cases
    
    enum FetchBeer {
        struct Response {
            var listBeer: [Beer]
        }
        struct ViewModel {
            struct BeerResumed {
                var imageUrl: String?
                var name: String
                var abv: String
            }
            var listBeer: [BeerResumed]
        }
    }
    enum Select {
        struct Request {
            var idx: Int
        }
    }
}

