//
//  ListBeerPresenter.swift
//  BeerList
//
//  Created by Lucas  N Santana on 24/07/19.
//  Copyright (c) 2019 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBeerPresentationLogic {
    func presentListBeers(response: ListBeer.FetchBeer.Response)
    func presentDetailBeer()
}

class ListBeerPresenter: ListBeerPresentationLogic {
    weak var viewController: ListBeerDisplayLogic?
    
    
    func presentListBeers(response: ListBeer.FetchBeer.Response) {
        var displayedBeers: [ListBeer.FetchBeer.ViewModel.BeerResumed] = []
        for beer in response.listBeer {
            let name = beer.name ?? "-"
            let abv = beer.abv != nil ? "abv: \(String(describing: beer.abv!))%" : ""
            let beerResumed = ListBeer.FetchBeer.ViewModel.BeerResumed(imageUrl: beer.imageURL,
                                                                       name: name,
                                                                       abv: abv)
            displayedBeers.append(beerResumed)
        }
        let viewModel = ListBeer.FetchBeer.ViewModel(listBeer: displayedBeers)
        viewController?.displayListBeers(viewModel: viewModel)
    }
    func presentDetailBeer(){
        viewController?.displayDetailBeer()
    }
}
